name: last_exam
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  card_scanner: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.7.2
  google_mlkit_text_recognition: ^0.15.0
  camera: ^0.10.5+5
  path_provider: ^2.1.2
  path: ^1.9.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
